### ISSUE TITLE
How i can remove the rounded border on the images

### ISSUE THREAD

**Issue by ivan-vilches** [bigbite/macy.js#54]
I see a bit of round on the images any way to remove that?
Thanks you

**Comment by jrmd** [comment]
Hi @ivan-vilches,

Do you have a demo of this happening? As macy doesnt add any border radius' to images or containers.

**Comment by JayHoltslander** [comment]
@jrmd I think you need:
````css
<style>
  .demo {
    border-radius: 0px;
  }
</style>
````
